// <auto-generated />
using System;
using EastParts.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EastParts.Data.Migrations
{
    [DbContext(typeof(EastPartsDbContext))]
    [Migration("20250512125913_patch1")]
    partial class patch1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EastParts.Data.Models.CarBrand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Brand Identification");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Brand Logo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasComment("Brand Name");

                    b.HasKey("Id");

                    b.ToTable("CarBrands");

                    b.HasData(
                        new
                        {
                            Id = new Guid("148c46b7-5930-4ce3-8bb0-658fd772c423"),
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/4/44/BMW.svg",
                            Name = "BMW"
                        },
                        new
                        {
                            Id = new Guid("149c57b8-5930-4ce3-8bb0-658fd772c423"),
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Mercedes-Logo.svg/1200px-Mercedes-Logo.svg.png",
                            Name = "Mercedes-Benz"
                        });
                });

            modelBuilder.Entity("EastParts.Data.Models.CarBrandModels", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Model Identification");

                    b.Property<Guid>("CarBrandId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Brand to whom it belongs");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Model Image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Model Name");

                    b.HasKey("Id");

                    b.HasIndex("CarBrandId");

                    b.ToTable("CarModels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("258c46b7-5930-4ce3-8bb0-658fd772c423"),
                            CarBrandId = new Guid("148c46b7-5930-4ce3-8bb0-658fd772c423"),
                            ImageUrl = "https://curvaconcepts.com/wp-content/uploads/silver-f30-bmw-340i-c300-4.jpg",
                            Name = "F30 340i"
                        },
                        new
                        {
                            Id = new Guid("259c46b7-5930-4ce3-8bb0-658fd772c424"),
                            CarBrandId = new Guid("149c57b8-5930-4ce3-8bb0-658fd772c423"),
                            ImageUrl = "https://www.litchfieldmotors.com/wp-content/uploads/w204_top_p-1700x850.jpg",
                            Name = "C-63"
                        });
                });

            modelBuilder.Entity("EastParts.Data.Models.PartCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Category Identification");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Category Image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Category Name");

                    b.HasKey("Id");

                    b.ToTable("PartCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("367c96b7-5930-4ce3-8bb0-658fd772c423"),
                            ImageUrl = "https://www.motortrend.com/uploads/f/31208710.jpg?w=768&width=768&q=75&format=webp",
                            Name = "Brake System"
                        },
                        new
                        {
                            Id = new Guid("368c96b7-5930-4ce3-8bb0-658fd772c423"),
                            ImageUrl = "https://media.istockphoto.com/id/1414449765/photo/wheel-structure-car-wheel-with-brake-isolated-on-a-white-background-3d-illustration.jpg?s=612x612&w=0&k=20&c=a8zRRvb0cbpPtjC7jMmqjVr5gKcNpx_ruPZJqPwGLYw=",
                            Name = "Wheel Suspension"
                        });
                });

            modelBuilder.Entity("EastParts.Data.Models.PartType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Part Type Identification");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Part Type Image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Part Type Name");

                    b.Property<Guid>("PartCategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Part Type belongs to a certain category");

                    b.HasKey("Id");

                    b.HasIndex("PartCategoryId");

                    b.ToTable("PartTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("420c96b7-5930-4ce3-8bb0-658fd772c423"),
                            ImageUrl = "https://mcprod.gsfcarparts.com/media/catalog/category/brake-pads_2.png",
                            Name = "Brake Pads",
                            PartCategoryId = new Guid("367c96b7-5930-4ce3-8bb0-658fd772c423")
                        },
                        new
                        {
                            Id = new Guid("421c19b3-6030-4ce3-8bb0-658fd772c423"),
                            ImageUrl = "https://www.h-r.com/wp-content/uploads/2022/11/HR-Tieferlegungsfedern-1.png",
                            Name = "Sport Springs",
                            PartCategoryId = new Guid("368c96b7-5930-4ce3-8bb0-658fd772c423")
                        });
                });

            modelBuilder.Entity("EastParts.Data.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Product Identification");

                    b.Property<Guid>("CarBrandModelsId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Product can be used for certain model");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasComment("Product description");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Image of the product");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasComment("Product manufacturer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasComment("Product Name");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Product price");

                    b.HasKey("Id");

                    b.HasIndex("CarBrandModelsId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("520c19b6-7030-4ce3-8bb0-658fd772c423"),
                            CarBrandModelsId = new Guid("258c46b7-5930-4ce3-8bb0-658fd772c423"),
                            Description = "BREMBO PRIME LINE pads for BMW 3 Series F30/F35/F80 340i",
                            ImageUrl = "https://www.autopower.bg/images/%D0%BD%D0%B0%D0%BA%D0%BB%D0%B0%D0%B4%D0%BA%D0%B8-BREMBO-PRIME-LINE-P06088-BMW-3-Sedan-F30-F35-F80-340-i-imagetabig-845520901720541-BREMBO.jpg",
                            Manufacturer = "Brembo",
                            Name = "BREMBO PRIME LINE pads",
                            Price = 243.00m
                        },
                        new
                        {
                            Id = new Guid("521c29b6-7030-4ce3-8bb0-658fd772c423"),
                            CarBrandModelsId = new Guid("259c46b7-5930-4ce3-8bb0-658fd772c424"),
                            Description = "BILSTEIN B3 OE Replacement for Mercedes C-Class W204 C-63 AMG",
                            ImageUrl = "https://www.autopower.bg/images/%D0%BF%D1%80%D1%83%D0%B6%D0%B8%D0%BD%D0%B0-BILSTEIN-B3-OE-Replacement-36-292141-Mercedes-C-class-Saloon-w204-C-63-AMG-204.077-imagetabig-845520896800921-BILSTEIN.jpg",
                            Manufacturer = "Bilstein",
                            Name = "BILSTEIN B3 OE Replacement",
                            Price = 135.00m
                        });
                });

            modelBuilder.Entity("EastParts.Data.Models.CarBrandModels", b =>
                {
                    b.HasOne("EastParts.Data.Models.CarBrand", "CarBrand")
                        .WithMany("CarBrandModels")
                        .HasForeignKey("CarBrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarBrand");
                });

            modelBuilder.Entity("EastParts.Data.Models.PartType", b =>
                {
                    b.HasOne("EastParts.Data.Models.PartCategory", "PartCategory")
                        .WithMany("PartTypes")
                        .HasForeignKey("PartCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PartCategory");
                });

            modelBuilder.Entity("EastParts.Data.Models.Product", b =>
                {
                    b.HasOne("EastParts.Data.Models.CarBrandModels", "CarBrandModels")
                        .WithMany("Products")
                        .HasForeignKey("CarBrandModelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarBrandModels");
                });

            modelBuilder.Entity("EastParts.Data.Models.CarBrand", b =>
                {
                    b.Navigation("CarBrandModels");
                });

            modelBuilder.Entity("EastParts.Data.Models.CarBrandModels", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("EastParts.Data.Models.PartCategory", b =>
                {
                    b.Navigation("PartTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
