// <auto-generated />
using System;
using EastParts.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EastParts.Data.Migrations
{
    [DbContext(typeof(EastPartsDbContext))]
    partial class EastPartsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EastParts.Data.Models.CarBrand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Brand Identification");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Brand Logo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasComment("Brand Name");

                    b.HasKey("Id");

                    b.ToTable("CarBrands");

                    b.HasData(
                        new
                        {
                            Id = new Guid("148c46b7-5930-4ce3-8bb0-658fd772c423"),
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/4/44/BMW.svg",
                            Name = "BMW"
                        },
                        new
                        {
                            Id = new Guid("a0d1f2e4-3c5b-4e8f-9a7c-6d5b1a2f3c4d"),
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Mercedes-Logo.svg/1200px-Mercedes-Logo.svg.png",
                            Name = "Mercedes-Benz"
                        });
                });

            modelBuilder.Entity("EastParts.Data.Models.CarBrandModels", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Model Identification");

                    b.Property<Guid>("CarBrandId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Brand to whom it belongs");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Model Image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Model Name");

                    b.HasKey("Id");

                    b.HasIndex("CarBrandId");

                    b.ToTable("CarModels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("258c46b7-5930-4ce3-8bb0-658fd772c423"),
                            CarBrandId = new Guid("148c46b7-5930-4ce3-8bb0-658fd772c423"),
                            ImageUrl = "https://curvaconcepts.com/wp-content/uploads/silver-f30-bmw-340i-c300-4.jpg",
                            Name = "F30"
                        },
                        new
                        {
                            Id = new Guid("259c46b7-5930-4ce3-8bb0-658fd772c424"),
                            CarBrandId = new Guid("a0d1f2e4-3c5b-4e8f-9a7c-6d5b1a2f3c4d"),
                            ImageUrl = "https://www.litchfieldmotors.com/wp-content/uploads/w204_top_p-1700x850.jpg",
                            Name = "C-63"
                        });
                });

            modelBuilder.Entity("EastParts.Data.Models.PartCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Category Identification");

                    b.Property<Guid>("CarBrandModelsId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Category belongs to a certain model");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Category Image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Category Name");

                    b.HasKey("Id");

                    b.HasIndex("CarBrandModelsId");

                    b.ToTable("PartCategories");
                });

            modelBuilder.Entity("EastParts.Data.Models.PartType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Part Type Identification");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Part Type Image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Part Type Name");

                    b.Property<Guid>("PartCategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Part Type belongs to a certain category");

                    b.HasKey("Id");

                    b.HasIndex("PartCategoryId");

                    b.ToTable("PartTypes");
                });

            modelBuilder.Entity("EastParts.Data.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Product Identification");

                    b.Property<Guid>("CarBrandId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Product can be used for certain brand");

                    b.Property<Guid>("CarBrandModelsId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Product can be used for certain model");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasComment("Product description");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Image of the product");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasComment("Product manufacturer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasComment("Product Name");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Product price");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasComment("Product quantity");

                    b.HasKey("Id");

                    b.HasIndex("CarBrandId");

                    b.HasIndex("CarBrandModelsId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("EastParts.Data.Models.CarBrandModels", b =>
                {
                    b.HasOne("EastParts.Data.Models.CarBrand", "CarBrand")
                        .WithMany("CarBrandModels")
                        .HasForeignKey("CarBrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarBrand");
                });

            modelBuilder.Entity("EastParts.Data.Models.PartCategory", b =>
                {
                    b.HasOne("EastParts.Data.Models.CarBrandModels", "CarBrandModels")
                        .WithMany("PartCategories")
                        .HasForeignKey("CarBrandModelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarBrandModels");
                });

            modelBuilder.Entity("EastParts.Data.Models.PartType", b =>
                {
                    b.HasOne("EastParts.Data.Models.PartCategory", "PartCategory")
                        .WithMany("PartTypes")
                        .HasForeignKey("PartCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PartCategory");
                });

            modelBuilder.Entity("EastParts.Data.Models.Product", b =>
                {
                    b.HasOne("EastParts.Data.Models.CarBrand", "CarBrand")
                        .WithMany("Products")
                        .HasForeignKey("CarBrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EastParts.Data.Models.CarBrandModels", "CarBrandModels")
                        .WithMany("Products")
                        .HasForeignKey("CarBrandModelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarBrand");

                    b.Navigation("CarBrandModels");
                });

            modelBuilder.Entity("EastParts.Data.Models.CarBrand", b =>
                {
                    b.Navigation("CarBrandModels");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("EastParts.Data.Models.CarBrandModels", b =>
                {
                    b.Navigation("PartCategories");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("EastParts.Data.Models.PartCategory", b =>
                {
                    b.Navigation("PartTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
